# Generated by GPT
from products.models import Product, ProductVariations
from ..models import Cart, CartItem
from rest_framework import generics, permissions
from ..serializers import CartItemSerializer
from rest_framework.response import Response
from django.db import transaction


# Helper function to get or create a session-based cart
def _cart_id(request):
    """
    Returns the session key for the current user's cart.
    If the session doesn't exist, it creates a new one.
    """
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


class CartAPIView(generics.GenericAPIView):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = CartItemSerializer

    def post(self, request, product_id, *args, **kwargs):
        """
        Handle adding a product (with optional variations) to the cart.
        If the same product with the same variations exists, increase quantity.
        Otherwise, create a new CartItem.
        """

        current_user = request.user
        product_variations = []

        # 1 Ensure the user is authenticated
        if current_user.is_authenticated:
            # 2 Get the product by ID
            try:
                product = Product.objects.get(id=product_id)
            except Product.DoesNotExist:
                return Response({"error": "Product not found"}, status=404)

            print(f"Adding product: {product.name}")

            # 3 Collect product variations from request.data (NOT request.POST)
            # DRF uses request.data for JSON input
            for key, value in request.data.items():
                if key.lower() in ['csrfmiddlewaretoken']:
                    continue
                try:
                    variation = ProductVariations.objects.get(
                        product=product,
                        variation_category__iexact=key,
                        variation_value__iexact=value,
                    )
                    product_variations.append(variation)
                except ProductVariations.DoesNotExist:
                    pass  # Ignore missing variations

            # 4 Get or create a Cart associated with this session
            cart_session_id = _cart_id(request)
            cart, created = Cart.objects.get_or_create(cart_id=cart_session_id)

            # 5 Check if this product already exists in the cart for this user
            cart_items = CartItem.objects.filter(product=product, user=current_user, cart=cart)

            existing_variation_list = []
            item_ids = []

            # 6 Gather existing variations for comparison
            for item in cart_items:
                existing_variations = list(item.variations.all())
                existing_variation_list.append(existing_variations)
                item_ids.append(item.id)

            # 7 If the same variation combination exists, increase quantity
            if product_variations and any(
                    set(v.id for v in existing) == set(v.id for v in product_variations)
                    for existing in existing_variation_list
            ):
                # Find matching item and increase quantity
                for index, existing in enumerate(existing_variation_list):
                    if set(v.id for v in existing) == set(v.id for v in product_variations):
                        item_id = item_ids[index]
                        cart_item = CartItem.objects.get(id=item_id)
                        cart_item.quantity += 1
                        cart_item.save()
                        print(f"Increased quantity for existing cart item ID: {cart_item.id}")
                        return Response({"message": "Cart item quantity updated"}, status=200)

            # 8 Otherwise, create a new CartItem
            with transaction.atomic():
                cart_item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    user=current_user,
                    cart=cart,  # FIXED: cart must always be linked
                )

                # Add product variations if present
                if product_variations:
                    cart_item.variations.set(product_variations)
                cart_item.save()

            print("New cart item created successfully.")

        else:
            return Response({"error": "Authentication required"}, status=401)

        return Response({"message": "Product added to cart"}, status=201)
