# Generated by Django 5.2.7 on 2025-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_active_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
